name: marcerVeinminer
version: 1.1.2
author: marcermarc
main: de.marcermarc.veinminer.Main
api-version: 1.14
commands:
  marcerVeinminer:
    description: Zum Einstellen des Plugins
    #usage: /marcerVeinminer [loadBlocks, saveBlocks, enable, disable, lists <tool> <block>]
  mV:
    description: Zum Einstellen des Plugins
    #usage: /mV [loadBlocks, saveBlocks, enable, disable, lists [add, remove] <tool> <block>]