name: marcerVeinminer
version: 1.1.3
author: marcermarc
main: de.marcermarc.veinminer.Main
api-version: "1.15"
commands:
  marcerVeinminer:
    description: Zum Einstellen des Plugins
  mV:
    description: Zum Einstellen des Plugins